### ISSUE TITLE
network traffic

### ISSUE THREAD

**Issue by nchapet** [dan-v/dosxvpn#18]
Hello,

first thank you for this program, very well done and very easy to use.

One question, however:
I wanted to know if all the network traffic went through the VPN or only the DNS requests?

thank you!

**Comment by dan-v** [comment]
@nchapet - glad to hear this is working well for you 👍 . All network traffic destined for the internet goes over the VPN. You could test this by going to a site like http://ipv6-test.com/ and verify that it's showing you the IP address of your DigitalOcean droplet. If you're seeing a DigitalOcean IP address this means you successfully passed network traffic through your VPN to that website. Also, you should see that you have an IPv6 address as well since the deployed droplet has both IPv4 and IPv6 addresses.

**Comment by nchapet** [comment]
Hello!

Thank you for this detailed answer! I asked myself the question, is it possible to only send DNS queries with strongSwan? To gain speed (as when using Pi-hole locally). :-)

**Comment by dan-v** [comment]
If you wanted to only send DNS queries through the VPN - you probably don't need a VPN and could just setup Pi-hole locally or remotely.

**Comment by nchapet** [comment]
Indeed you are right. But I'm mainly looking to access the Pi-hole ad blocker remotely from a cellular connection on iOS and I believe (unless I'm wrong?) that the VPN is the only way.

**Comment by dan-v** [comment]
Ah, yeah unfortunately when on cellular connection most mobile OS's don't give you access to change DNS settings. Seems like VPN is your best bet. I'd recommend encrypting all your traffic when on cellular data anyways. In terms of speed, I'd just suggestion picking the datacenter closest to your location.

That said, it probably is possible to configure strongSwan to only pass traffic for DNS. The current setup creates a dummy interface with IP address 1.1.1.1 and this is what DNS gets set to for clients when connected to VPN. So you could configure strongSwan to only pass a route for 1.1.1.1 instead of all traffic, which in theory would only pass DNS traffic through the VPN. Probably not a scenario that I am looking to support though.

**Comment by nchapet** [comment]
Thanks a lot for your help. that's exactly what I'm trying to do, but I recognize that for the moment I lack some knowledge to make the VPN work like this. But I will find how to do it! Thanks again.

**Comment by dan-v** [comment]
You may want to give this a shot: https://www.dnsoverride.com/. I've never used it - but it appears to setup a dummy VPN on iOS that allows you to set DNS server on wifi and mobile. One issue with this approach is that since DNS traffic is not actually flowing over VPN, it can be intercepted by a mobile carrier and redirected to their DNS server (a lot of mobile carriers do this). Anyways, going to close this issue - hopefully that gets you headed in the right direction.
